### ISSUE TITLE
hide hud bleach when activating f3

### ISSUE THREAD

**Issue by LDoom** [HerraVp/BleachHack-VpEdition#11]
make BH hud  hide when activating f3

![image](https://user-images.githubusercontent.com/73355762/128528568-bde9da65-45f9-44b3-8c85-88e88603419a.png)

bps are hidden when activating f3
![image](https://user-images.githubusercontent.com/73355762/128528665-3a1b3cca-e73e-415e-b0f2-c4814b872b8f.png)

this is the same in original BH.

**Comment by HerraVp** [comment]
https://github.com/HerraVp/BleachHack-VpEdition/actions/runs/1106005956
