### ISSUE TITLE
add break bedrock 

### ISSUE THREAD

**Issue by LDoom** [HerraVp/BleachHack-VpEdition#6]
Bleach epearl edition and cupedition were discontinued /:  for 1.17

![image](https://user-images.githubusercontent.com/73355762/124331807-a0b74300-db55-11eb-992a-334ec1f5492d.png)

https://github.com/22s/bleachhack-1.16-epearl-edition (original module)
https://github.com/CUPZYY/BleachHack-CupEdition

**Comment by HerraVp** [comment]
I'll add it soon.

**Comment by HerraVp** [comment]
Its added now in the recent dev build. https://github.com/HerraVp/BleachHack-VpEdition/actions
