### ISSUE TITLE
Add ToggleMSGs

### ISSUE THREAD

**Issue by LDoom** [HerraVp/BleachHack-VpEdition#8]
:
![image](https://user-images.githubusercontent.com/73355762/125953346-2b46a67e-a66f-4af1-9e55-a338e1948cab.png)

https://github.com/ChiquitaV2/MacHack

**Comment by HerraVp** [comment]
I added ToggleMSGs now. Download the latest dev build from https://github.com/HerraVp/BleachHack-VpEdition/actions
